# Generated by Django 3.0.7 on 2020-08-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='washer',
            name='test',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
