# Generated by Django 3.0.7 on 2020-08-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0002_washer_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washer',
            name='test',
        ),
    ]
