# Generated by Django 3.0.7 on 2020-08-08 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0003_remove_washer_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashType',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='washer',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='washer',
            name='close_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='washer',
            name='open_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='washer',
            name='phone',
            field=models.CharField(default='010-0000-000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='washer',
            name='wash_type',
            field=models.ManyToManyField(to='car_wash.WashType'),
        ),
    ]
