# Generated by Django 3.0.7 on 2020-08-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0004_auto_20200808_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washer',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='washer',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='washer',
            name='wash_type',
        ),
    ]
