# Generated by Django 3.0.7 on 2020-08-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0009_auto_20200808_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washer',
            name='city',
            field=models.CharField(default='서울시', max_length=7),
        ),
        migrations.AlterField(
            model_name='washer',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
