# Generated by Django 3.0.7 on 2020-08-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0010_auto_20200808_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washer',
            name='address',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
