# Generated by Django 3.0.7 on 2020-08-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0011_auto_20200808_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='washer',
            name='wash_type',
            field=models.ManyToManyField(to='car_wash.WashType'),
        ),
    ]
