# Generated by Django 3.0.7 on 2020-08-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0012_washer_wash_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='washer',
            name='open_sat',
            field=models.CharField(default='09:00-18:00', max_length=20),
        ),
        migrations.AddField(
            model_name='washer',
            name='open_sun',
            field=models.CharField(default='99:99-99:99', max_length=20),
        ),
        migrations.AddField(
            model_name='washer',
            name='open_week',
            field=models.CharField(default='09:00-18:00', max_length=20),
        ),
    ]
