# Generated by Django 3.0.7 on 2020-09-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0014_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='washer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='car_wash.Washer'),
        ),
    ]
