# Generated by Django 3.0.7 on 2020-09-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0015_auto_20200902_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.CharField(default='내용이 없습니다.', max_length=100),
        ),
    ]
