# Generated by Django 3.0.7 on 2020-09-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0016_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(default='내용이 없습니다.', max_length=500),
        ),
    ]
