# Generated by Django 3.0.7 on 2020-08-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.CharField(default='ID', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='account_pw',
            field=models.CharField(default='PW', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
